### ISSUE TITLE
Add option to align buttons to left/right

### ISSUE THREAD

**Issue by lucasbento** [panz3r/hyper-spotify#11]
This way the buttons don't change the position based on the size of the song name:

![](https://user-images.githubusercontent.com/6207220/30053096-f31fa8a6-9227-11e7-902e-8d4f742563f9.gif)

**Comment by panz3r** [comment]
Hi @lucasbento ,
Thanks for your suggestion, I was indeed looking for a way to solve this "alignment" issue.

**Comment by panz3r** [comment]
Hi @lucasbento 
I just released a beta version of `hyper-spotify` with a new `controlsPosition` option.

If you'd like to give it a try, you should be able to install it
- by running (if you're using [hpm](https://github.com/zeit/hpm)) 
```bash
$ hpm install hyper-spotify@beta
```
- or by adding the version `#2.1.0-beta.1` inside `~/.hyper.js` like this
```js
module.exports = {
  ...
  plugins: ['hyper-spotify#2.1.0-beta.1']
  ...
}
```

And then simply update your `~/.hyper.js` as follow
```js
modules.exports = {
  config: {
    ...
    hyperSpotify: {
      position: 'top', // or 'bottom'
      controlsPosition: 'default', // or 'left' or 'right'
    },
    ...
  },
  ... 
};
```

Please let me know if it works as you expected

**Comment by lucasbento** [comment]
@panz3r: awesome!

Just tested it and works perfectly!

Using `controlsPosition: 'left'`:
![kapture 2017-09-06 at 8 51 02](https://user-images.githubusercontent.com/6207220/30098041-99511986-92e0-11e7-96c1-591737dacc07.gif)

**Comment by panz3r** [comment]
@lucasbento , Thanks again for your feedback.
I'll publish this feature soon.

**Comment by lucasbento** [comment]
@panz3r: no problem, thank you for being so quickly!
