### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by balazsorban44** [panz3r/hyper-spotify#13]
Hi, I get the following problem after installing your plugin on Hyper 2.0.4

![image](https://user-images.githubusercontent.com/18369201/31546391-66e1ab4a-b023-11e7-884d-33862c6aa8af.png)

I also tried the provided installing method in README.md

What should I do?

**Comment by panz3r** [comment]
Hi @balazsorban44 ,
Thanks for your feedback.

You can try to re-compile the `abstract-socket` module as explained in the error message.
To do so, run the following
```bash
$ cd ~/.hyper_plugins && npm install abstract-socket
```

Let me know if it works.

**Comment by balazsorban44** [comment]
Unfortunately, it did not help either.

**Comment by panz3r** [comment]
Can you please run `node -v` and `npm version` and paste the results here

**Comment by balazsorban44** [comment]
I have node v8.6.0 and npm 5.4.2 installed.

**Comment by panz3r** [comment]
Hi @balazsorban44 ,

I just released a new version of Hyper-spotify (`v3.0.0`) and I tested it on Ubuntu 17.04 with `node 8.7.0` and `nom 5.5.1`.

Can you try to remove `hyper-spotify` plugin and add it again.

**Comment by balazsorban44** [comment]
Unfortunately, I still get the same error.

**Comment by panz3r** [comment]
Hi @balazsorban44 ,

Can you try to run the following commands and post here the resulting files
```bash
$ cd ~/.hyper_plugins
$ npm ls > ~/npm_deps_tree.txt
$ ls > ~/npm_deps_list.txt
```

**Comment by panz3r** [comment]
Closed due to inactivity

**Comment by dimitrisraptis96** [comment]
Same error here @panz3r 😕

- DevTools error message:
![image](https://user-images.githubusercontent.com/24657754/51088854-b65e0580-176d-11e9-8a63-3543a4301ee1.png)

- Output of `npm ls` command:

```
npm ERR! missing: abstract-socket@2.0.0, required by hyper-plugins@0.0.1
npm ERR! missing: hyper-spotify@^5.0.2, required by hyper-plugins@0.0.1
npm ERR! missing: hypercwd@^1.3.0, required by hyper-plugins@0.0.1
npm ERR! missing: hyperline@latest, required by hyper-plugins@0.0.1
npm ERR! missing: bindings@1.3.1, required by abstract-socket@2.0.0
npm ERR! missing: nan@2.12.1, required by abstract-socket@2.0.0
```

- Node version is **v10.11.0**
- npm version is **6.4.1**

**Comment by OrionNebula** [comment]
I've seen this before - you have to run `electron-rebuild` in your Hyper plugin directory. `abstract-socket` probably uses a native add-on, which must be recompiled for electron. You might also have to locate and specify the electron version Hyper uses when you run it.

**Comment by dimitrisraptis96** [comment]
@OrionNebula how could I specify the electron version Hyper uses?

**Comment by OrionNebula** [comment]
It's one of the command line arguments to `electron-rebuild`, I don't remember the specific one. You can find the electron version for Hyper by reading the value of `process.versions.electron` in the dev console, as far as I know.

**Comment by dimitrisraptis96** [comment]
You were 💯 correct @OrionNebula! 

The above problem solved by rebuilding `abstract-socket` using the following command:
`~/.hyper_plugins/node_modules/.bin/electron-rebuild -v [output of process.versions.electron]` 

Thank you so much 👏

**Comment by panz3r** [comment]
@dimitrisraptis96 thanks for your feedback and also thanks to @OrionNebula for the solution.
I'll add this to the troubleshooting section of the README.
