### ISSUE TITLE
Cannot install - error occured in mapHyperState

### ISSUE THREAD

**Issue by tomdurkin** [panz3r/hyper-spotify#18]
Hi, 

I'd love to use this plugin but I can't seem to get it to install. I get the following error: 

Running: 
Hyper 1.4.8 (stable)
macOS Sierra 10.12.6

Error:
`[Notification] Plugin error: hyper-spotify: Error occurred in `mapHyperState`. Check Developer Tools for details.`

Any help sorting this out would be appreciated, thanks!

**Comment by xlanor** [comment]
Getting this error too - Using version 2.1.1 on Fedora 26.

**Comment by panz3r** [comment]
Hi @tomdurkin and @xlanor ,

Thanks for your feedback and I'm sorry that `hyper-spotify` latest release caused you issues.
I just pushed a new update and it will be available soon.

You should be able to update the plugin by going to `Plugins > Update` in the Hyper top-menu.
New version is 3.1.1 and you can see your installed one by going to `Hyper > About Hyper`

Thanks for your patience.

**Comment by tomdurkin** [comment]
@panz3r - Just reinstalled and it works a charm! Thanks for sorting it out.

**Comment by xlanor** [comment]
Thanks for the fix, I'll test it out later!
