### ISSUE TITLE
error: Plugin does not expose API

### ISSUE THREAD

**Issue by jcreamer898** [panz3r/hyper-spotify#19]
Seeing the following error on a fresh install.

![](http://d.pr/i/GOlwXw+)

Already tried the cd and npm install thing from the README.

Any advice?

No dev tools errors either. 

Using 1.4.8 on High Sierra.

**Comment by panz3r** [comment]
Hi @jcreamer898 ,

Can you please run the following commands and attach the resulting files?
```bash
$ cd ~/.hyper_plugins
$ npm ls > ~/npm_deps_tree.txt
$ ls ./node_modules > ~/npm_deps_list.txt
```

**Comment by jcreamer898** [comment]
![](http://d.pr/i/toK0aK+)

**Comment by jcreamer898** [comment]
Tree -> http://d.pr/f/JylisT
List -> http://d.pr/f/4L4Xmn

**Comment by panz3r** [comment]
Hi @jcreamer898 ,

Thanks for the quick feedback, it seems you installed the wrong plugin.
`spotify` (https://www.npmjs.com/package/spotify) is not this plugin, but a node module, you should install `hyper-spotify`.

**Comment by jcreamer898** [comment]
lol figures, thanks!

**Comment by panz3r** [comment]
Thanks for your interest in this plugin!
