### ISSUE TITLE
Place song name underneath a centered control center

### ISSUE THREAD

**Issue by keeganjk** [panz3r/hyper-spotify#20]
Could you center the control buttons (`|< ( || ) >|`) and put the song name underneath them so that I don't have to move my mouse back and forth if trying to skip multiple times?

**Comment by panz3r** [comment]
Hi @keeganjk ,

Thanks for your feedback, to solve your issue you can try to use `controlsPosition` setting.
If you set it to `left` or `right`, the controls won't move around.

See [README](https://github.com/panz3r/hyper-spotify#configuration) for more info.
