### ISSUE TITLE
Is it supposed to work with Hyper 2.1.0-canary.2?

### ISSUE THREAD

**Issue by balazsorban44** [panz3r/hyper-spotify#24]
Hi, I just downloaded this plugin for my Hyper, but nothing happens. There are no errors, but nothing shows up either. Tried bottom, top, and different margins, with no effect. I am using the latest `2.1.0-canary.2`

**Comment by tinalai** [comment]
I'm experience the same problem on Hyper 2.0.0(stable). 'hyper-spotify' does not show up in the list of plugins when you click on the Hyper dropdown > About Hyper.

I have also tried removing the plugin, moving the order of the plugins to before `'hyper-statusline'`.

**Comment by panz3r** [comment]
Hi @balazsorban44 and @tinalai ,

Thanks for your feedback, I'm currently using `hyper-spotify 5.0.0` on `Hyper 2.0.0 (stable)` and don't have any issues.

Can you try to change the plugin order as suggested [here](https://github.com/panz3r/hyper-spotify/issues/15#issuecomment-342390126)?

If this doesn't work, you can try to force-install the plugin by adding the plugin inside `.hyper.js`, saving the file, closing Hyper and running the following commands 
```sh
cd ~/.hyper_plugins && npm install
```
You should find the plugin listed inside the `About Hyper` dialog.

Let me know if this solves your issue.

**Comment by panz3r** [comment]
Hi @balazsorban44 , 

Maybe I've found the issue, version 5.0.0 of the plugin is not getting installed correctly.
If you are not on Windows, you can safely install version 4.0.0 by adding this to your `.hyper.js` configuration
```js
plugins: ['hyper-spotify#4.0.0'],
```
This should work.

While you can use this version, I'll update this issue as soon as a fixed version will be available.

**Comment by panz3r** [comment]
@balazsorban44 , @tinalai, @waitan666,

Published version `5.0.1`, Hyper should auto-update but you can also force update by going to `Plugins > Update` menu.

Let me know if this update fixes your issue.

**Comment by tinalai** [comment]
Hi @panz3r, 
Thanks, version `5.0.1` solved the loading problem. I now see the hyper-spotify bar. Everything seems to work except for the `margin` configuration fyi.

 I use the `hyper-statusline` plugin as well, and if the `hyper-spotify` `position` is set to default, `margin` set to `double` the control bar is still on the same position and behind the statusline, making the spotify controls unclickable.

**Comment by panz3r** [comment]
Hi @tinalai ,

Thanks for your feedback, I'm going to close this issue so I opened issue #25 to keep track of the `margin` issue and I'm already working on a fix.
