### ISSUE TITLE
Margin setting is ignored

### ISSUE THREAD

**Issue by panz3r** [panz3r/hyper-spotify#25]
I use the `hyper-statusline` plugin as well, and if the `hyper-spotify` `position` is set to default, `margin` set to `double` the control bar is still on the same position and behind the statusline, making the spotify controls unclickable.

_Originally posted by @tinalai in https://github.com/panz3r/hyper-spotify/issues/24#issuecomment-436341420_

**Comment by panz3r** [comment]
Fixed in `v5.0.2`

**Comment by sreetamdas** [comment]
Issue is present again in `v5.3.1`
