### ISSUE TITLE
Song info goes blank

### ISSUE THREAD

**Issue by adriankarlen** [panz3r/hyper-spotify#34]
The song info is only set when a song ends "naturally". So when clicking next the song info will be blank. 

Moreover the song info seems to go blank after a while during playing. This seems to happen at different times, I've had it not happen, happen after about 2 minutes and happening after about 20 seconds.

What I have found is that for some reason the call `this.spotifymanager.getTrack()` seems to not return artist and song name but all other information. I tried looking into [spotifyjs](https://www.npmjs.com/package/spotifyjs) but that project seems to be since long abandoned.

**Comment by panz3r** [comment]
Hi @adriankarlen ,

Thanks for your feedback.

I haven't faced this issue in my previous testing and usages, which OS are you having this issue on? 


> What I have found is that for some reason the call this.spotifymanager.getTrack() seems to not return artist and song name but all other information. I tried looking into spotifyjs but that project seems to be since long abandoned.

Internally `hyper-spotify` uses this library to interact with Spotify [`spotify-js`](https://github.com/panz3r/spotify-js)

**Comment by adriankarlen** [comment]
I'm using macOS Catalina. 10.15.2 to be precise. Ah okay, that library is more up to date :)

Well as I said before this problem occurs when the getTack-function don't return track name or artist. So far it seems to be really inconsistent about when it occurs. From what I see your library uses [`spotify-node-applescript`](https://github.com/andrehaveman/spotify-node-applescript), perhaps it's that one that's causing troubles.

**Comment by alexpriest** [comment]
Same issue here. Thanks in advance!

**Comment by adriankarlen** [comment]
After some research online I found this forum [thread](https://community.spotify.com/t5/Spotify-for-Developers/Apple-OSA-script-not-returning-playback-information-for-new/td-p/4940507). So this seems to be a general problem with Spotify and not the plugin.
