### ISSUE TITLE
Margin issue with hyperline

### ISSUE THREAD

**Issue by aewing** [panz3r/hyper-spotify#4]
Great plugin. I'm seeing a margin issue when combined with Hyperline. Commands will ocassionally disappear behind one bar or the other. Either plugin works without issue until combined.

This is particularly troublesome with vim:
![hyper-vim-overflow](https://user-images.githubusercontent.com/5033161/27100898-8049e628-5034-11e7-816c-77748185a7d9.png)

**Comment by brianveltman** [comment]
You can set the padding in .hyper.js to solve this.
` // custom padding (css format, i.e.: `top right bottom left`)
    padding: '5px 5px 35px 5px',
`

**Comment by mackelito** [comment]
Same issue here

**Comment by mckernanin** [comment]
I edited line 35 of HyperSpotifyFooter.js, to bump the Spotify bar above hyperline. This will definitely get broken in an update, it'd be good to have a better way to address this.
