### ISSUE TITLE
Please make it compatible with the linux lords out there

### ISSUE THREAD

**Issue by admazzola** [panz3r/hyper-spotify#6]

**Comment by panz3r** [comment]
Hi @admazzola, Thanks for your feedback. I’ll consider adding Linux OS support in the next version, I already checked the viability of supporting it and I think it won’t take long.

**Comment by panz3r** [comment]
Hi @admazzola, 
I just released an alpha version of `hyper-spotify` supporting Linux OS.

If you'd like to give it a try, you should be able to install it
- by running (if you're using [hpm](https://github.com/zeit/hpm)) 
```bash
$ hpm install hyper-spotify@next
```
- or by adding the version `#2.0.0-alpha.2` inside `~/.hyper.js` like this
```js
module.exports = {
  ...
  plugins: ['hyper-spotify#2.0.0-alpha.2']
  ...
}
```

I tested it on `Ubuntu 17.04` and it seems to be working fine.

**Comment by admazzola** [comment]
It works :D :D

**Comment by panz3r** [comment]
Hi @admazzola,
I just release version `2.0.0` as stable, you can now install it without the need to specify version inside `~/.hyper.js`
